[project]
name = "uk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas",
    "openpyxl",
    "tqdm",
    "geopy",
    #"shapely",
    "geopandas",
    #"exactextract",
    "xarray[io]",
    "rioxarray",
    "rasterio",
    "rasterstats",
    "matplotlib",
    "libpysal",
    "scipy",
    "spreg",
    "esda",
    "seaborn",
    "ipykernel",
    "ipywidgets",
]
